services:
  backend:
    build:
      context: ./backend
    container_name: abac_backend
    env_file:
      - .env
    environment:
      # из контейнера подключаемся к PostgreSQL на хосте (Windows/Mac)
      DATABASE_URL: postgresql://postgres:1234@host.docker.internal:5432/postgres
      CORS_ORIGINS: http://localhost:5173
      OLLAMA_HOST: http://host.docker.internal:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: abac_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
